### ISSUE TITLE
Can I have the parameters for "The Map to End All Maps" and "Jurusalem" maps?

### ISSUE THREAD

**Issue by swfsql** [jkunimune15/Map-Projections#1]
Please share. They are awesome!

edit: I noticed The Jerusalem is "Perice Quincuncial" with your "Jesuralem" preset.
Could you inform "The Map to End All Maps" one, if you still have it?

**Comment by jkunimune15** [comment]
I don't remember exactly. It was a Guyou projection, with the pole somewhere in the neighbourhood of 24°, -151°, 61°, and the left part of the image (Indonesia, Australia, and Antarctica) moved over to the right in an image editor.

**Comment by swfsql** [comment]
Thanks a lot! I'll be looking into it :)
