### ISSUE TITLE
Equations for AuthaGraph

### ISSUE THREAD

**Issue by lazarusA** [jkunimune15/Map-Projections#3]
Hello,
great work. I did not found the equations for the AuthaGraph representation. Could point me out to them? Thanks.

**Comment by jkunimune15** [comment]
Sure thing. The math for AuthaGraph in this repo is in the `AUTHAGRAPH` object in [Polyhedral.java](https://github.com/jkunimune15/Map-Projections/blob/master/src/maps/Polyhedral.java), but it's not the most readable. I have it formatted more nicely and explained in words on [my website](https://kunimune.home.blog/2017/11/23/the-secrets-of-the-authagraph-revealed/).
