### ISSUE TITLE
Add country border/names

### ISSUE THREAD

**Issue by yaminb** [jkunimune15/Map-Projections#5]
Add an option to show country borders and names

**Comment by mapsmak353478** [comment]
It is not a cartographic modeling software like QGIS. It takes an image and transforms it into another projection.

It's up to you to use an input image that includes borders, country names etc...

You can use software like QGIS to create a custom map and use it as input.

**Comment by jkunimune15** [comment]
This would be nice, but I agree with mapsmak353478 that it's out of the scope of this software. I believe if you use an SVG file with country names included as text, the MapDesignerVector will place them properly.

**Comment by yaminb** [comment]
just a note.
I tried this. Ended up paying for a digital world map with country names.

obviously things are skewed a bit, but looks relatively good.
