### ISSUE TITLE
Modifying the graticule

### ISSUE THREAD

**Issue by TJung1968** [jkunimune15/Map-Projections#7]
Hello,

I think it would be great if you could modify the line color and width of the graticule that MapDesignerRaster is drawing. Depending on the input image you’re projecting, the white lines can be almost invisible – and depending on the size of the exported image, the lines may be too thin (on very large images) or too thick (and small images).

The most convenient thing would be input fields within the applications’ main windows, but I also would be fine with a CSS file (or a JSON file, or a plain text .inf file or whatever) which is parsed when you hit the "Update Map" button and right before rendering the exported image.

Kind regards,
Tobias Jung

**Comment by jkunimune15** [comment]
I had considered doing this in the past with a popup window that lets you choose a color and thickness, but I decided it was too much work.  Reading the settings from a text file would be much easier for me, though.  I'll try to implement something like this this week.

**Comment by jkunimune15** [comment]
I have done this.  If you install the latest release, there should be a file called `graticule.txt` with five numbers in it.  The first three are the RGB values from 0 to 255, the fourth is the opacity from 0 to 255, and the fifth is the line width in pixels.  I think that should work for basic use cases.

**Comment by TJung1968** [comment]
Wow, that was fast!
Works like a charm and enables me to create various graticule files for specific purposes, copy them to a folder having an appropriate name, to copy them back whenever I need them.

Thanks a lot! :-)
