### ISSUE TITLE
ubiquitous Shapefile or modern geojson support for vector input?

### ISSUE THREAD

**Issue by tumagonx** [jkunimune15/Map-Projections#8]
While svg is the vector output of browser rendering, do you plan to support SHP and GeoJSON? they are more prevalent as datasource format.

**Comment by tumagonx** [comment]
Does input needed to be already in WGS projection?

**Comment by jkunimune15** [comment]
I've considered implementing SHP, but I don't plan to because I don't work on this project actively.

Input needs to be in an equirectangular projection.  I don't account for any deviations from a sphere, so there will be some level of error regardless of what coordinate system you use.

**Comment by tumagonx** [comment]
ok, nevermind I can use gdal to make svg. I wish libproj4 have support for discontinued projections like yours.
